# Generated by Django 4.0 on 2021-12-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='island_name', max_length=100)),
                ('last_number', models.IntegerField()),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name_plural': 'MASTER PULAU',
            },
        ),
        migrations.RemoveField(
            model_name='province',
            name='last_number',
        ),
        migrations.AddField(
            model_name='province',
            name='pulau',
            field=models.ForeignKey(blank=True, db_column='id_pulau', null=True, on_delete=django.db.models.deletion.SET_NULL, to='userAuth.island'),
        ),
    ]
